In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
df=pd.read_csv("cibil_nn.csv")

In [3]:
df.head()

,Unnamed: 0,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,45,46,12,7,5,7,4,0.583,0.333,0.417,...,1.0,0.615,1.000,7.729,0,0,CC,others,651,P4
1,183,184,9,5,4,0,0,0.000,0.000,0.444,...,1.0,0.286,0.286,23.113,0,0,PL,others,672,P2
2,351,352,4,0,4,1,0,0.250,0.000,1.000,...,0.0,0.000,0.000,5.582,0,1,HL,CC,689,P2
3,403,404,129,122,7,0,7,0.000,0.054,0.054,...,1.0,0.500,0.429,2.218,1,0,ConsumerLoan,AL,649,P4
4,493,494,4,1,3,1,0,0.250,0.000,0.750,...,1.0,0.333,1.000,6.192,0,0,PL,PL,662,P3

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 585 entries, 0 to 584
Data columns (total 88 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    585 non-null    int64
 1   PROSPECTID                    585 non-null    int64
 2   Total_TL                      585 non-null    int64
 3   Tot_Closed_TL                 585 non-null    int64
 4   Tot_Active_TL                 585 non-null    int64
 5   Total_TL_opened_L6M           585 non-null    int64
 6   Tot_TL_closed_L6M             585 non-null    int64
 7   pct_tl_open_L6M               585 non-null    float64
 8   pct_tl_closed_L6M             585 non-null    float64
 9   pct_active_tl                 585 non-null    float64
 10  pct_closed_tl                 585 non-null    float64
 11  Total_TL_opened_L12M          585 non-null    int64
 12  Tot_TL_closed_L12M            585 non-null    int64
 13  pct_tl_open_L12M              585 non-null    float64
 14  pct_tl_closed_L12M            585 non-null    float64
 15  Tot_Missed_Pmnt               585 non-null    int64
 16  Auto_TL                       585 non-null    int64
 17  CC_TL                         585 non-null    int64
 18  Consumer_TL                   585 non-null    int64
 19  Gold_TL                       585 non-null    int64
 20  Home_TL                       585 non-null    int64
 21  PL_TL                         585 non-null    int64
 22  Secured_TL                    585 non-null    int64
 23  Unsecured_TL                  585 non-null    int64
 24  Other_TL                      585 non-null    int64
 25  Age_Oldest_TL                 585 non-null    int64
 26  Age_Newest_TL                 585 non-null    int64
 27  time_since_recent_payment     585 non-null    int64
 28  time_since_first_deliquency   585 non-null    int64
 29  time_since_recent_deliquency  585 non-null    int64
 30  num_times_delinquent          585 non-null    int64
 31  max_delinquency_level         585 non-null    int64
 32  max_recent_level_of_deliq     585 non-null    int64
 33  num_deliq_6mts                585 non-null    int64
 34  num_deliq_12mts               585 non-null    int64
 35  num_deliq_6_12mts             585 non-null    int64
 36  max_deliq_6mts                585 non-null    int64
 37  max_deliq_12mts               585 non-null    int64
 38  num_times_30p_dpd             585 non-null    int64
 39  num_times_60p_dpd             585 non-null    int64
 40  num_std                       585 non-null    int64
 41  num_std_6mts                  585 non-null    int64
 42  num_std_12mts                 585 non-null    int64
 43  num_sub                       585 non-null    int64
 44  num_sub_6mts                  585 non-null    int64
 45  num_sub_12mts                 585 non-null    int64
 46  num_dbt                       585 non-null    int64
 47  num_dbt_6mts                  585 non-null    int64
 48  num_dbt_12mts                 585 non-null    int64
 49  num_lss                       585 non-null    int64
 50  num_lss_6mts                  585 non-null    int64
 51  num_lss_12mts                 585 non-null    int64
 52  recent_level_of_deliq         585 non-null    int64
 53  tot_enq                       585 non-null    int64
 54  CC_enq                        585 non-null    int64
 55  CC_enq_L6m                    585 non-null    int64
 56  CC_enq_L12m                   585 non-null    int64
 57  PL_enq                        585 non-null    int64
 58  PL_enq_L6m                    585 non-null    int64
 59  PL_enq_L12m                   585 non-null    int64
 60  time_since_recent_enq         585 non-null    int64
 61  enq_L12m                      585 non-null    int64
 62  enq_L6m                       585 non-null    int64
 63  enq_L3m                       585 non-null    int64
 64  MARITALSTATUS                 585 non-null    object
 65  EDUCATION                     585 non-null    object
 66  AGE                           585 non-null    int64
 67  GENDER                        585 non-null    object
 68  NETMONTHLYINCOME              585 non-null    int64
 69  Time_With_Curr_Empr           585 non-null    int64
 70  pct_of_active_TLs_ever        585 non-null    float64
 71  pct_opened_TLs_L6m_of_L12m    585 non-null    float64
 72  pct_currentBal_all_TL         585 non-null    float64
 73  CC_utilization                585 non-null    float64
 74  CC_Flag                       585 non-null    int64
 75  PL_utilization                585 non-null    float64
 76  PL_Flag                       585 non-null    int64
 77  pct_PL_enq_L6m_of_L12m        585 non-null    float64
 78  pct_CC_enq_L6m_of_L12m        585 non-null    float64
 79  pct_PL_enq_L6m_of_ever        585 non-null    float64
 80  pct_CC_enq_L6m_of_ever        585 non-null    float64
 81  max_unsec_exposure_inPct      585 non-null    float64
 82  HL_Flag                       585 non-null    int64
 83  GL_Flag                       585 non-null    int64
 84  last_prod_enq2                585 non-null    object
 85  first_prod_enq2               585 non-null    object
 86  Credit_Score                  585 non-null    int64
 87  Approved_Flag                 585 non-null    object
dtypes: float64(16), int64(66), object(6)
memory usage: 402.3+ KB

In [5]:
df.columns

Index(['Unnamed: 0', 'PROSPECTID', 'Total_TL', 'Tot_Closed_TL',
       'Tot_Active_TL', 'Total_TL_opened_L6M', 'Tot_TL_closed_L6M',
       'pct_tl_open_L6M', 'pct_tl_closed_L6M', 'pct_active_tl',
       'pct_closed_tl', 'Total_TL_opened_L12M', 'Tot_TL_closed_L12M',
       'pct_tl_open_L12M', 'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'Auto_TL',
       'CC_TL', 'Consumer_TL', 'Gold_TL', 'Home_TL', 'PL_TL', 'Secured_TL',
       'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL',
       'time_since_recent_payment', 'time_since_first_deliquency',
       'time_since_recent_deliquency', 'num_times_delinquent',
       'max_delinquency_level', 'max_recent_level_of_deliq', 'num_deliq_6mts',
       'num_deliq_12mts', 'num_deliq_6_12mts', 'max_deliq_6mts',
       'max_deliq_12mts', 'num_times_30p_dpd', 'num_times_60p_dpd', 'num_std',
       'num_std_6mts', 'num_std_12mts', 'num_sub', 'num_sub_6mts',
       'num_sub_12mts', 'num_dbt', 'num_dbt_6mts', 'num_dbt_12mts', 'num_lss',
       'num_lss_6mts', 'num_lss_12mts', 'recent_level_of_deliq', 'tot_enq',
       'CC_enq', 'CC_enq_L6m', 'CC_enq_L12m', 'PL_enq', 'PL_enq_L6m',
       'PL_enq_L12m', 'time_since_recent_enq', 'enq_L12m', 'enq_L6m',
       'enq_L3m', 'MARITALSTATUS', 'EDUCATION', 'AGE', 'GENDER',
       'NETMONTHLYINCOME', 'Time_With_Curr_Empr', 'pct_of_active_TLs_ever',
       'pct_opened_TLs_L6m_of_L12m', 'pct_currentBal_all_TL', 'CC_utilization',
       'CC_Flag', 'PL_utilization', 'PL_Flag', 'pct_PL_enq_L6m_of_L12m',
       'pct_CC_enq_L6m_of_L12m', 'pct_PL_enq_L6m_of_ever',
       'pct_CC_enq_L6m_of_ever', 'max_unsec_exposure_inPct', 'HL_Flag',
       'GL_Flag', 'last_prod_enq2', 'first_prod_enq2', 'Credit_Score',
       'Approved_Flag'],
      dtype='object')

In [7]:
df.describe()

,Unnamed: 0,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,...,PL_utilization,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,Credit_Score
count,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,...,585.000000,585.0,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000,585.000000
mean,25600.707692,25601.707692,14.517949,8.170940,6.347009,1.849573,1.328205,0.146655,0.083145,0.553010,...,0.724156,1.0,0.422656,0.326350,0.250899,0.193287,242.707275,0.379487,0.150427,677.547009
std,14981.649883,14981.649883,12.873998,10.922744,3.722975,2.290825,1.882228,0.163755,0.107114,0.229431,...,0.250704,0.0,0.419381,0.410247,0.306609,0.284189,3889.132647,0.485675,0.357796,28.276308
min,45.000000,46.000000,2.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.047000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.444000,0.000000,0.000000,561.000000
25%,13186.000000,13187.000000,6.000000,2.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.379000,...,0.623000,1.0,0.000000,0.000000,0.000000,0.000000,7.101000,0.000000,0.000000,662.000000
50%,24711.000000,24712.000000,11.000000,5.000000,6.000000,1.000000,1.000000,0.105000,0.050000,0.538000,...,0.783000,1.0,0.333000,0.000000,0.133000,0.000000,11.362000,0.000000,0.000000,676.000000
75%,38895.000000,38896.000000,18.000000,10.000000,8.000000,3.000000,2.000000,0.222000,0.143000,0.692000,...,0.918000,1.0,0.909000,0.667000,0.400000,0.333000,18.981000,1.000000,0.000000,694.000000
max,51282.000000,51283.000000,129.000000,122.000000,24.000000,16.000000,11.000000,0.889000,0.600000,1.000000,...,1.044000,1.0,1.000000,1.000000,1.000000,1.000000,83672.100000,1.000000,1.000000,795.000000

In [8]:
df = df.drop(columns=['Unnamed: 0', 'PROSPECTID'])

In [9]:
y = df['Credit_Score']

In [10]:
X = df[['AGE']]

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [12]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [13]:
y_pred = model.predict(X_test)

In [14]:
mse = mean_squared_error(y_test, y_pred)

In [15]:
r2 = r2_score(y_test, y_pred)

In [16]:
n = len(y_test)

In [17]:
p = X.shape[1]

In [18]:
adj_r2 = 1 - ((1 - r2) * (n - 1) / (n - p - 1))

In [20]:
print("Loss (MSE):", mse)
print("R² Score:", r2)
print("Adjusted R²:", adj_r2)

Loss (MSE): 576.0494014369077
R² Score: 0.16840581965631296
Adjusted R²: 0.16117456591419388

In [ ]:
# X = df[['AGE', 'NETMONTHLYINCOME']]

In [22]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [23]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [24]:
y_pred = model.predict(X_test)

In [25]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

n = len(y_test)
p = X.shape[1]

adj_r2 = 1 - ((1-r2)*(n-1)/(n-p-1))

In [26]:

print("Loss (MSE):", mse)
print("R2 Score:", r2)
print("Adjusted R2:", adj_r2)

Loss (MSE): 582.0382495632089
R2 Score: 0.1597602221843405
Adjusted R2: 0.14501917345073245

In [ ]:
# X = df[['AGE', 'NETMONTHLYINCOME', 'Total_TL']]

In [29]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [31]:
y_pred = model.predict(X_test)

In [32]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

n = len(y_test)
p = X.shape[1]

adj_r2 = 1 - ((1-r2)*(n-1)/(n-p-1))

In [33]:

print("Loss (MSE):", mse)
print("R2 Score:", r2)
print("Adjusted R2:", adj_r2)

Loss (MSE): 570.3924453371543
R2 Score: 0.17657229246104156
Adjusted R2: 0.15471137987151173

In [48]:
# X = df[[
#     'AGE',
#     'NETMONTHLYINCOME',
#     'Total_TL',
#     'Tot_Active_TL',
#     'CC_utilization',
#     'PL_utilization',
#     'tot_enq',
#     'Time_With_Curr_Empr',
#     'num_std',
#     'pct_tl_open_L6M',
#     'pct_tl_closed_L6M',
#     'pct_active_tl',
#     'pct_closed_tl',
#     'time_since_recent_payment'
# ]]

In [39]:

print("Loss (MSE):", mse)
print("R2 Score:", r2)
print("Adjusted R2:", adj_r2)

Loss (MSE): 503.8980344480891
R2 Score: 0.2725646934301187
Adjusted R2: 0.2258486645678328

In [ ]:
# X = df[[
#     'AGE',
#     'NETMONTHLYINCOME',
#     'Total_TL',
#     'Tot_Closed_TL',
#     'Tot_Active_TL',
#     'CC_TL',
#     'PL_TL',
#     'Consumer_TL',
#     'Gold_TL',
#     'Home_TL',
#     'Secured_TL',
#     'Unsecured_TL',
#     'Other_TL',
#     'Age_Oldest_TL',
#     'Age_Newest_TL',
#     'time_since_recent_payment',
#     'time_since_recent_deliquency',
#     'num_times_delinquent',
#     'max_recent_level_of_deliq',
#     'num_deliq_6mts',
#     'num_deliq_12mts',
#     'tot_enq',
#     'CC_enq',
#     'PL_enq',
#     'CC_utilization',
#     'PL_utilization',
#     'Time_With_Curr_Empr',
#     'pct_of_active_TLs_ever',
#     'pct_currentBal_all_TL',
#     'max_unsec_exposure_inPct'
# ]]

In [52]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

n = len(y_test)
p = X.shape[1]

adj_r2 = 1 - ((1-r2)*(n-1)/(n-p-1))

In [53]:

print("Loss (MSE):", mse)
print("R2 Score:", r2)
print("Adjusted R2:", adj_r2)

Loss (MSE): 215.53499469537277
R2 Score: 0.6888502152732284
Adjusted R2: 0.5803095926941221

In [54]:
X = df.drop(columns=['Credit_Score'])
y = df['Credit_Score']

In [56]:
obj_cols = X.select_dtypes(include='object').columns
X = pd.get_dummies(X, columns=obj_cols, drop_first=True)

In [57]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [58]:
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

n = len(y_test)
p = X.shape[1]

adj_r2 = 1 - ((1-r2)*(n-1)/(n-p-1))

In [59]:

print("Loss (MSE):", mse)
print("R2 Score:", r2)
print("Adjusted R2:", adj_r2)

Loss (MSE): 34.71626976409063
R2 Score: 0.9498830346372276
Adjusted R2: 0.6366520011198998